requires 'perl', '5.024000';
requires 'Mouse';
requires 'Smart::Args';
requires 'Mojolicious';
requires 'Aniki';
requires 'Anego', '== 0.01_02';
requires 'Config::PL';
requires 'Set::Object';
requires 'Mojolicious::Plugin::AssetPack';
requires 'Mojolicious::Plugin::ProxyPassReverse::SubDir';
